/** Cross-check owner: compares supplied evidence/results, never prices, adopts
 * geometry/rules, fetches remote data, emits clearance or approves investment. */
import {diligenceHash} from './protocol-diligence.mjs';
import {assessTemporalCurrency,evidenceTimestamp} from './temporal.mjs';
export const CROSS_AUDIT_VERSION='areas-cross-audit-1.0.0';
const list=x=>Array.isArray(x)?x:[],finite=x=>typeof x==='number'&&Number.isFinite(x),hash=x=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x);
const slug=x=>typeof x==='string'&&/^[a-z0-9][a-z0-9-]{0,79}$/.test(x);
const personal=/(?:^|[^\d])(?:\d{11}|\d{14}|\d{3}\.\d{3}\.\d{3}-\d{2}|\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2})(?:$|[^\d])/;
const safeId=x=>typeof x==='string'&&/^[a-zA-Z][a-zA-Z0-9_:.-]{0,119}$/.test(x)&&!personal.test(x)&&!/(?:cpf|cnpj|token|secret|owner)/i.test(x)?x:null;
const norm=x=>typeof x==='string'?x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim():null;
const states=['supported','partial','sem_base','conflict','error','negative','not_applicable'];
const aggregate=checks=>checks.some(x=>x.state==='conflict')?'conflict':checks.some(x=>x.state==='error')?'error':checks.every(x=>x.state==='not_applicable')?'not_applicable':checks.every(x=>['supported','not_applicable'].includes(x.state))?'supported':checks.some(x=>['supported','partial','negative'].includes(x.state))?'partial':'sem_base';
const same=(object,key,value)=>object?.[key]==null?null:object[key]===value;
export function buildCrossAudit({study,assessment=study?.assessment,verification=study?.verification,landValuation,result,protocol,now=new Date().toISOString()}={}){
 if(!slug(study?.slug)||evidenceTimestamp(now)===null)throw TypeError('Terreno e relógio válidos são obrigatórios para a auditoria.');
 const dimensions=[],actions=[],s=study.slug,aligned={assessment:same(assessment,'slug',s),verification:verification?.studySlug==null?null:verification.studySlug===s,land:same(landValuation?.subject,'slug',s),result:result?.studySlug===s,protocol:protocol?.slug===s};
 const dimension=(id,label)=>{const d={id,label,checks:[]};dimensions.push(d);return d;};
 const check=(d,id,label,state,finding,{severity='P1',owner='remote',action=null,evidence='Evidência do mesmo lote, com fonte, data, escopo e integridade.',impact='Admissibilidade da análise',sourceIds=[],evidenceIds=[]}={})=>{
  const actionId=['supported','not_applicable'].includes(state)?null:'audit-'+id;
  d.checks.push({id,label,state,severity,finding,actionId,sourceIds:sourceIds.map(safeId).filter(Boolean),evidenceIds:evidenceIds.map(safeId).filter(Boolean)});
  if(actionId)actions.push({id:actionId,checkId:id,owner,priority:severity,label:action??('Verificar '+label.toLowerCase()+'.'),evidence,impact,remoteFirst:true});
 };
 const identity=dimension('identity','Identidade e escopo territorial');
 const mismatches=Object.entries(aligned).filter(([k,v])=>v===false&&({assessment:assessment,verification,land:landValuation,result,protocol})[k]);
 const bound=Object.values(aligned).filter(value=>value===true).length,unbound=Object.values(aligned).filter(value=>value===null).length;
 check(identity,'same_parcel','Mesmo lote em todas as leituras',mismatches.length?'conflict':!bound?'sem_base':unbound?'partial':'supported',mismatches.length?'Há respostas de outro lote; seus dados não qualificam esta análise.':!bound?'Vínculo parcelar ainda não foi informado pelas leituras recebidas.':unbound?'Os identificadores presentes coincidem; há leituras sem vínculo explícito ao lote.':'Todas as leituras recebidas identificam o mesmo lote.',{severity:'P0',action:mismatches.length?'Conciliar a identificação do lote e repetir somente as leituras divergentes.':'Comprovar o vínculo das leituras recebidas ao mesmo lote.'});
 const land=aligned.land?landValuation:null,r=aligned.result?result:null,p=aligned.protocol?protocol:null,v=aligned.verification!==false?verification:null,a=aligned.assessment?assessment:null;
 const subject=land?.subject;
 const municipalConflict=subject&&(norm(subject.municipality)!==norm(study.municipality)||subject.uf!==study.uf);
 check(identity,'municipal_scope','Município e UF da comparação',municipalConflict?'conflict':subject&&study.municipality&&study.uf?'supported':'sem_base',municipalConflict?'O escopo territorial do comparador diverge do cadastro.':subject&&study.municipality&&study.uf?'Comparador e cadastro conservam município e UF.':'Identidade municipal ainda não está completa.',{severity:'P0',action:'Conciliar cadastro municipal e enquadramento do comparador.'});
 const geometryAxis=list(a?.regulatory?.axes).find(x=>x.id==='identity_geometry'),g=study.siteReview?.geometry;
 check(identity,'geometry_binding','Reconciliação da área e perímetro',geometryAxis?.state==='blocked'?'conflict':g?.legalAdoption===true?'supported':'partial',geometryAxis?.state==='blocked'?'A avaliação de admissibilidade identifica divergência que impede adoção do perímetro.':g?.legalAdoption===true?'Adoção declarada pela leitura geométrica.':'A geometria continua como referência; conciliar os papéis antes da adoção.',{severity:'P0',owner:'specialist',action:'Conciliar cadastro, registro, perímetro e acesso com evidência habilitada.',impact:'Área disponível, direitos, uso e preço por unidade'});
 const units=dimension('units','Unidades e papéis de área');
 check(units,'reference_area','Área de referência válida',finite(study.areaM2)&&study.areaM2>0?'supported':'error',finite(study.areaM2)&&study.areaM2>0?'Área de referência expressa em m²; não equivale automaticamente a área utilizável.':'Área de referência ausente ou inválida.',{severity:'P0'});
 const areaAligned=!subject||!finite(subject.areaM2)||!finite(study.areaM2)?null:Math.abs(subject.areaM2-study.areaM2)<=.01;
 check(units,'price_area_binding','Mesmo denominador no preço da terra',areaAligned===true?'supported':areaAligned===false?'conflict':'sem_base',areaAligned===true?'A comparação física usa a área do cadastro, preservando sua origem.':areaAligned===false?'Comparador e cadastro usam áreas diferentes.':'Denominador da comparação ainda não está identificado.',{severity:'P0',action:'Reconciliar a área-base do comparador e o cadastro, sem escalar geometria.'});
 const estimate=land?.estimate,unitKnown=['BRL_m2','BRL_ha'].includes(estimate?.displayUnit);
 const scale=estimate?.displayUnit==='BRL_ha'?10000:1;
 const unitConsistent=unitKnown&&finite(estimate?.unitCentralBrl)&&finite(estimate?.unitPerM2Brl)?Math.abs(estimate.unitCentralBrl-estimate.unitPerM2Brl*scale)<=.01:null;
 check(units,'market_unit','Unidade monetária da comparação',unitConsistent===true?'supported':unitConsistent===false?'conflict':'sem_base',unitConsistent===true?'Unitário em m²/ha compatível com a avaliação, sem misturar terra e área construída.':unitConsistent===false?'Há incompatibilidade entre unitários de m² e ha.':'Unidade unitária ainda precisa de lastro.',{severity:'P0'});
 const temporal=dimension('currency','Atualidade e vigência das bases'),currency=assessTemporalCurrency(v?.at,{now});
 check(temporal,'receipt_binding','Vínculo do recibo ao terreno',aligned.verification===true?'supported':aligned.verification===false?'conflict':'sem_base',aligned.verification===true?'Recibo declara o mesmo terreno.':aligned.verification===false?'Recibo declara outro terreno; não pode ser reutilizado.':'Metadado do recibo não informa vínculo parcelar; conservar data sem adotar suas conclusões.',{severity:'P0'});
 check(temporal,'receipt_currency','Atualidade operacional do recibo',!v?'sem_base':['future','invalid-date'].includes(currency.status)?'error':currency.status==='expired'||v.freshness?.status!=='current'?'partial':'supported',!v?'Recibo do mesmo terreno não foi recebido.':currency.status==='expired'?'O prazo operacional do recibo venceu; conservar a data histórica e repetir consultas.':currency.status==='current'&&v.freshness?.status==='current'?'Recibo no prazo operacional; vigência jurídica continua questão própria.':'Recibo não pode ser tratado como atual.',{severity:'P0',action:'Reexecutar consultas remotas e vincular novo recibo às entradas atuais.'});
 const datedSources=[...list(land?.sources),...list(r?.sources),...list(study.sources)];
 const sourceDates=datedSources.map(x=>evidenceTimestamp(x.capturedAt??x.checkedAt??x.retrievedAt??x.date)),knownDates=sourceDates.filter(at=>at!==null),future=knownDates.some(at=>at>evidenceTimestamp(now));
 check(temporal,'source_dates','Temporalidade das fontes recebidas',future?'error':!knownDates.length?'sem_base':knownDates.length<datedSources.length?'partial':'supported',future?'Há captura datada no futuro; conferir relógio e origem.':!knownDates.length?'Datas de captura ainda não foram fornecidas.':knownDates.length<datedSources.length?'Parte das fontes informa captura; completar a temporalidade das demais.':'As fontes datadas não apresentam captura futura; vigência é verificação própria.',{severity:'P0'});
 const proofs=dimension('evidence','Integridade e ligações de prova');
 const content=p?Object.fromEntries(Object.entries(p).filter(([key])=>key!=='basisHash')):null,protocolIntegrity=p?hash(p.basisHash)&&diligenceHash(content)===p.basisHash:null;
 check(proofs,'protocol_binding','Integridade do protocolo',protocolIntegrity===true?'supported':protocolIntegrity===false?'error':'sem_base',protocolIntegrity===true?'Protocolo íntegro e vinculado ao lote.':protocolIntegrity===false?'Hash do protocolo não corresponde ao conteúdo.':'Protocolo consolidado não recebido.',{severity:'P0'});
 const evidenceRows=list(p?.provenance?.evidence),unproven=evidenceRows.filter(e=>e.state==='supported'&&!hash(e.source?.sha256));
 check(proofs,'supported_evidence','Conclusões apoiadas por prova íntegra',unproven.length?'error':evidenceRows.length?'supported':'sem_base',unproven.length?'Há conclusão apoiada sem hash de sua evidência.':evidenceRows.length?'Evidências declaradas pelo protocolo têm ligação de integridade.':'Evidência parcelar corrente ainda não foi recebida.',{severity:'P0'});
 const knownEvidence=new Set(evidenceRows.map(x=>x.id)),broken=list(p?.fronts).flatMap(f=>list(f.checks)).flatMap(c=>list(c.evidenceIds)).filter(id=>!knownEvidence.has(id));
 check(proofs,'evidence_links','Links dos checks para as provas',broken.length?'error':p?'supported':'sem_base',broken.length?'Há check citando evidência ausente no recibo do protocolo.':p?'Referências de checks não apontam para evidência inexistente.':'Protocolo ausente impede verificar os links.',{severity:'P0'});
 const outcomes=aligned.verification===true?list(v?.checks).map(c=>c.status):[],errors=outcomes.filter(x=>['falha-temporaria','restrito'].includes(x)),negative=outcomes.filter(x=>x==='sem-resultados-na-consulta');
 check(proofs,'query_outcomes','Resultados negativos e falhas separados',errors.length?'error':negative.length?'negative':aligned.verification===true?'supported':'sem_base',errors.length?`${errors.length} consultas falharam ou são restritas; isso não é inexistência de incidência.`:negative.length?`${negative.length} consultas negativas conservam seu escopo; não são certidões de liberação.`:aligned.verification===true?'Estados das consultas permanecem distintos.':'Consultas parcelarias vinculadas não recebidas.',{severity:'P1'});
 const market=dimension('market','Amostra de mercado e independência'),rows=list(land?.comparables),ids=list(estimate?.sourceIds),selected=rows.filter(x=>ids.includes(x.id));
 const missingIds=ids.filter(id=>!rows.some(x=>x.id===id));
 check(market,'market_sample_binding','Faixa vinculada à amostra selecionada',missingIds.length?'conflict':ids.length?'supported':'sem_base',missingIds.length?'Faixa referencia amostras ausentes na avaliação.':ids.length?'IDs da faixa estão presentes nos comparáveis da avaliação.':'Ainda não há faixa vinculada a amostra externa.',{severity:'P0'});
 const duplicate=new Set(),seen=new Set();for(const x of selected){const key=x.assetKey??x.id;if(seen.has(key))duplicate.add(key);seen.add(key);}
 check(market,'independent_assets','Duplicatas de ativos selecionados',duplicate.size?'conflict':selected.length?'supported':'sem_base',duplicate.size?`${duplicate.size} réplicas do mesmo ativo aparecem na faixa selecionada.`:selected.length?'A amostra selecionada não repete o identificador de ativo informado.':'Amostra selecionada ausente.',{severity:'P0',action:'Deduplicar por identidade do imóvel na base de mercado.'});
 const publishers=new Set(selected.map(x=>x.publisher).filter(Boolean)),publisherConflict=finite(estimate?.independentPublisherCount)&&estimate.independentPublisherCount>publishers.size;
 check(market,'publisher_independence','Independência dos publicadores',publisherConflict?'conflict':publishers.size>1?'supported':publishers.size===1?'partial':'sem_base',publisherConflict?'Contagem de independência supera os publicadores presentes nas amostras.':publishers.size?`${publishers.size} publicadores identificados na faixa; referências do mesmo publicador não são fontes independentes.`:'Publicadores da amostra ainda não identificados.',{severity:'P1'});
 check(market,'land_separation','Terra e benfeitorias separadas',land?.flags?.improvementsUnseparated||!land?.landOnlyEstimate&&!land?.bareLandEstimate?'partial':land?'supported':'sem_base',land?.flags?.improvementsUnseparated?'Amostra contém contribuição de benfeitorias ainda não segregada; não atribuir tudo a terra.':land?.landOnlyEstimate||land?.bareLandEstimate?'A avaliação identifica referência de terra independente; condições da amostra permanecem.':'Terra independente ainda não está isolada.',{severity:'P1'});
 const critical=dimension('critical','Completude crítica do diagnóstico'),protocolChecks=list(p?.fronts).flatMap(f=>list(f.checks)),openCritical=protocolChecks.filter(c=>c.priority==='P0'&&!['supported','not_applicable'].includes(c.state));
 check(critical,'critical_checks','Verificações determinantes ainda abertas',openCritical.length?'partial':p?'supported':'sem_base',openCritical.length?`${openCritical.length} verificações críticas precisam de conclusão específica do lote.`:p?'Nenhum check crítico aberto no escopo recebido.':'Pauta crítica ainda não recebida.',{severity:'P0',action:'Encerrar critérios críticos em pesquisa remota, campo ou especialista conforme o protocolo.'});
 const regBlocked=list(a?.regulatory?.axes).filter(x=>x.state==='blocked');
 check(critical,'regulatory_gate','Admissibilidade normativa do estudo',regBlocked.length?'conflict':a?.regulatory?'partial':'sem_base',regBlocked.length?'A avaliação regulatória impede adoção de parte das conclusões; isso não afirma proibição jurídica.':a?.regulatory?'Cobertura preliminar registrada; não equivale a licença ou autorização.':'Leitura regulatória não recebida.',{severity:'P0',owner:'specialist',action:'Resolver a causa de inadmissibilidade com prova competente.'});
 const scenario=dimension('scenario','Consistência do cenário econômico');
 const financial=r?.base?.metrics,price=r?.recommendedPriceBrl,ceiling=r?.ceilings?.effectiveBrl;
 check(scenario,'scenario_available','Cenário do mesmo lote calculado',financial?'supported':r?.status==='invalid'?'error':'sem_base',financial?'Métricas recebidas do cálculo canônico do mesmo lote.':'Cenário válido ainda não recebido.',{severity:'P0'});
 const ordered=finite(price)&&finite(ceiling)?price<=ceiling+.01:null;
 check(scenario,'price_ceiling','Preço sugerido compatível com o teto',ordered===true?'supported':ordered===false?'conflict':'sem_base',ordered===true?'Preço sugerido não supera a capacidade calculada pelo cenário.':ordered===false?'Preço sugerido supera o teto fornecido pelo mesmo cenário.':'Preço e teto não disponíveis no cenário.',{severity:'P0'});
 const ledger=list(r?.base?.rows),badLedger=ledger.some(x=>!Number.isInteger(x.month)||!finite(x.projectBrl)||!finite(x.equityBrl))||ledger.some((x,i)=>i&&x.month<=ledger[i-1].month);
 check(scenario,'ledger_consistency','Fluxo ordenado e valores finitos',badLedger?'error':ledger.length?'supported':'sem_base',badLedger?'Fluxo contém número inválido ou mês fora de ordem.':ledger.length?'Fluxo canônico mantém ordem, zeros e valores negativos.':'Fluxo do cenário não recebido.',{severity:'P0'});
 const escalation=r?.investmentApproved===true||r?.adoptedMarketValueBrl!=null||p?.capabilities?.investmentReady===true;
 check(scenario,'authority','Cálculo separado da aprovação',escalation?'conflict':'supported',escalation?'Há tentativa de tratar cálculo preliminar como aprovação ou valor adotado.':'Auditoria e cálculo não aprovam investimento nem adotam valor de mercado.',{severity:'P0'});
 for(const d of dimensions){d.state=aggregate(d.checks);d.severity=d.checks.filter(c=>!['supported','not_applicable'].includes(c.state)).sort((a,b)=>a.severity.localeCompare(b.severity))[0]?.severity??null;}
 const all=dimensions.flatMap(d=>d.checks),counts=Object.fromEntries(states.map(state=>[state,all.filter(x=>x.state===state).length])),covered=all.filter(x=>!['sem_base','not_applicable'].includes(x.state)).length;
 const payload={schemaVersion:1,version:CROSS_AUDIT_VERSION,slug:s,checkedAt:now,state:aggregate(all),dimensions,actions:actions.sort((a,b)=>a.priority.localeCompare(b.priority)),counts,
  coverage:{eligible:all.filter(c=>c.state!=='not_applicable').length,examined:covered,supported:counts.supported,criticalOpen:all.filter(c=>c.severity==='P0'&&!['supported','not_applicable'].includes(c.state)).length,scorePct:null,meaning:'Contagem de checks de consistência; não é probabilidade de viabilidade ou valorização.'},
  provenance:{protocolHash:hash(p?.basisHash)?p.basisHash:null,verificationId:safeId(v?.id),inputHash:hash(v?.inputSha256)?v.inputSha256:null,calculationInputHash:hash(r?.inputSha256)?r.inputSha256:null,currency:{status:currency.status,receiptState:['current','stale','unbound','unverifiable'].includes(v?.freshness?.status)?v.freshness.status:'absent',receiptAt:evidenceTimestamp(v?.at)!==null?v.at:null},sourceCounts:{selectedAssets:selected.length,independentPublishers:publishers.size,protocolEvidence:evidenceRows.length,negativeQueries:negative.length,failedOrRestrictedQueries:errors.length}},
  ml:{state:'abstained',reason:'Sem artefato validado para este regime e praça; checks determinísticos continuam operacionais.',canReplaceCanonicalPrice:false,canApproveInvestment:false},canApproveInvestment:false,legalClearance:false,normativeAdoption:false};
 return {...payload,basisHash:diligenceHash(payload)};
}
